---
- name: Update system packages
  ansible.builtin.yum:
    name: "*"
    state: latest

- name: Install Apache & MariaDB
  ansible.builtin.yum:
    name:
      - httpd
      - mariadb105-server
    state: present

- name: Start and enable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - httpd
    - mariadb

- name: Secure MariaDB installation
  ansible.builtin.command: mysql -u root -p{{ db_root_password }} -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ db_root_password }}'; DELETE FROM mysql.user WHERE User=''; DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1'); DROP DATABASE IF EXISTS test; FLUSH PRIVILEGES;"
  changed_when: false

- name: Creating the needed DB in MariaDB
  ansible.builtin.shell: |
    mysql -u root -p{{ db_root_password }} -e "CREATE DATABASE {{ wp_db_name }};"
    mysql -u root -p{{ db_root_password }} -e "CREATE USER '{{ wp_db_user }}'@'localhost' IDENTIFIED BY '{{ wp_db_password }}';"
    mysql -u root -p{{ db_root_password }} -e "GRANT ALL PRIVILEGES ON {{ wp_db_name }}.* TO '{{ wp_db_user }}'@'localhost';"
    mysql -u root -p{{ db_root_password }} -e "FLUSH PRIVILEGES;"
  args:
    executable: /bin/bash
  changed_when: false


- name: Install PHP 8.2 and required modules
  ansible.builtin.dnf:
    name:
      - php8.2
      - php-mysqlnd
      - php-fpm
      - php-json
      - php-mbstring
      - php-xml
      - php-cli
      - php-gd
      - php-curl
    state: present
  notify: Restart Apache

- name: Download and extract WordPress
  ansible.builtin.shell: |
    cd {{ document_root }}
    curl -O https://wordpress.org/latest.tar.gz
    tar -xzf latest.tar.gz
    mv wordpress/* .
    cp wp-config-sample.php wp-config.php  # Add this line to create the config file
    rm -rf wordpress latest.tar.gz
  args:
    executable: /bin/bash
  changed_when: false

- name: Set correct permissions
  ansible.builtin.file:
    path: "{{ document_root }}"
    owner: apache
    group: apache
    mode: '0755'
    recurse: true
  changed_when: false

- name: Configure WordPress database connection
  ansible.builtin.lineinfile:
    path: "{{ document_root }}/wp-config.php"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: true
  loop:
    - { regexp: "define\\s*\\(\\s*'DB_NAME'\\s*,\\s*'.*'\\s*\\)\\s*;", line: "define( 'DB_NAME', '{{ wp_db_name }}' );" }
    - { regexp: "define\\s*\\(\\s*'DB_USER'\\s*,\\s*'.*'\\s*\\)\\s*;", line: "define( 'DB_USER', '{{ wp_db_user }}' );" }
    - { regexp: "define\\s*\\(\\s*'DB_PASSWORD'\\s*,\\s*'.*'\\s*\\)\\s*;", line: "define( 'DB_PASSWORD', '{{ wp_db_password }}' );" }
    - { regexp: "define\\s*\\(\\s*'DB_HOST'\\s*,\\s*'.*'\\s*\\)\\s*;", line: "define( 'DB_HOST', 'localhost' );" }
  notify: Restart Apache
  changed_when: false
